build:
    environment:
        php:
            version: 7.1
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=coverage-file --stop-on-failure'
                coverage:
                    file: 'coverage-file'
                    format: 'clover'
